import fs from 'fs';

import path from 'path';

import { PATHS } from '../paths.js';

import type { TestPlanCase } from '../types/prd.js';
import { resolveBaseUrlSync, normalizeBaseUrl } from './playwrightRunner.js';

import { entityToTestIdSlug } from './testId.js';



export const CI_TEST_SUBDIR = path.join('tests', 'deepsight');



export function loadTestPlanCases(projectPath: string): TestPlanCase[] | null {

  const paths = [

    path.join(projectPath, '.deepsight', 'test-plan.json'),

    path.resolve(projectPath, PATHS.FRONTEND_TEST_PLAN),

    path.resolve(projectPath, PATHS.BACKEND_TEST_PLAN),

  ];

  for (const fp of paths) {

    if (!fs.existsSync(fp)) continue;

    try {

      const raw = JSON.parse(fs.readFileSync(fp, 'utf-8'));

      if (Array.isArray(raw)) return raw as TestPlanCase[];

      if (raw.testCases && Array.isArray(raw.testCases)) return raw.testCases as TestPlanCase[];

    } catch {

      continue;

    }

  }

  return null;

}



function escapeStr(s: string): string {

  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

}



function specFileName(planId: string): string {

  const safe = planId.replace(/[^a-zA-Z0-9-]/g, '_').slice(0, 40);

  return `deepsight-${safe}.spec.ts`;

}



/** Doc 11 selector order: data-testid → aria role → landmark fallback */

function emitAssertionLines(tc: TestPlanCase): string[] {

  const lines: string[] = [];

  const route = tc.linkedRoutes[0] ?? '/';

  const isHome = route === '/' || route === '';



  lines.push(`    const main = page.getByRole('main');`);

  lines.push(`    if (await main.count()) {`);

  lines.push(`      await expect(main).toBeVisible();`);

  lines.push(`    } else {`);

  lines.push(`      await expect(page.locator('body')).toBeVisible();`);

  lines.push(`    }`);



  if (isHome) {
    lines.push(`    const h1 = page.getByRole('heading', { level: 1 }).first();`);
    lines.push(`    if (await h1.count()) await expect(h1).toBeVisible();`);
  }



  for (const entity of tc.linkedEntities.slice(0, 2)) {

    const slug = entityToTestIdSlug(entity);

    if (!slug) continue;

    const testId = `deepsight-${slug}`;

    lines.push(`    // Prefer stable selector: add data-testid="${testId}" in app`);

    lines.push(`    const el_${slug.replace(/-/g, '_')} = page.getByTestId('${escapeStr(testId)}');`);

    lines.push(`    if (await el_${slug.replace(/-/g, '_')}.count()) {`);

    lines.push(`      await expect(el_${slug.replace(/-/g, '_')}).toBeVisible();`);

    lines.push(`    }`);

  }



  return lines;

}



/**

 * Generate Playwright specs from generate_test_plan output (doc 04 / 11).

 */

export async function writePlaywrightFromPlan(

  projectPath: string,

  options: { planId?: string; testIds?: string[] } = {},

): Promise<{

  files: string[];

  testCaseCount: number;

  outputDirs: string[];

}> {

  let cases = loadTestPlanCases(projectPath);

  if (!cases?.length) {

    throw new Error('NO_TEST_PLAN');

  }



  if (options.testIds?.length) {

    cases = cases.filter((c) => options.testIds!.includes(c.id));

  }



  const baseUrl = resolveBaseUrlSync(projectPath);



  const dirs = [

    path.resolve(projectPath, CI_TEST_SUBDIR),

    path.resolve(projectPath, PATHS.TEST_CODE_DIR),

  ];

  for (const d of dirs) {

    fs.mkdirSync(d, { recursive: true });

  }



  const lines: string[] = [

    `import { test, expect } from '@playwright/test';`,

    ``,

    `/** Generated by DeepSight generate_test_code — selector order: data-testid → getByRole → body */`,

    `const BASE = '${escapeStr(baseUrl)}';`,

    ``,

    `test.describe('DeepSight generated plan', () => {`,

  ];



  for (const tc of cases) {

    const routes = tc.linkedRoutes.length ? tc.linkedRoutes : ['/'];

    const route = routes[0]!;

    const url =

      route === '/'

        ? `${baseUrl}/`

        : `${baseUrl}${route.startsWith('/') ? route : `/${route}`}`;

    const safeTitle = escapeStr(tc.title.slice(0, 80));

    lines.push(`  test('${tc.id}: ${safeTitle}', async ({ page }) => {`);

    for (const step of tc.steps.slice(0, 5)) {

      lines.push(`    // ${step.replace(/\n/g, ' ')}`);

    }

    lines.push(`    const res = await page.goto('${escapeStr(url)}');`);

    lines.push(`    expect(res?.status()).toBeLessThan(500);`);

    lines.push(...emitAssertionLines(tc));

    lines.push(`  });`);

    lines.push('');

  }



  lines.push(`});`);



  const fileName = specFileName(options.planId ?? 'plan');

  const written: string[] = [];

  for (const dir of dirs) {

    const fp = path.join(dir, fileName);

    fs.writeFileSync(fp, lines.join('\n'), 'utf-8');

    written.push(path.relative(projectPath, fp).replace(/\\/g, '/'));

  }



  const marker = path.resolve(projectPath, PATHS.ENRICHED_MARKER);

  fs.writeFileSync(marker, new Date().toISOString(), 'utf-8');



  return {

    files: written,

    testCaseCount: cases.length,

    outputDirs: dirs.map((d) => path.relative(projectPath, d).replace(/\\/g, '/')),

  };

}



const STRICT_MAIN_BODY =
  /await expect\((?:main|page\.getByRole\('main'\))\.or\((?:page\.)?locator\('body'\)\)\)\.toBeVisible\(\)/g;

const FIXED_MAIN_BODY = `if (await page.getByRole('main').count()) {
      await expect(page.getByRole('main')).toBeVisible();
    } else {
      await expect(page.locator('body')).toBeVisible();
    }`;



/** Align hardcoded localhost URLs and fragile locators in existing specs with dashboard base URL. */

export function syncSpecBaseUrls(projectPath: string, baseUrl: string): number {

  const normalized = normalizeBaseUrl(baseUrl);

  let port = '80';

  try {

    port = new URL(`${normalized}/`).port || '80';

  } catch {

    /* keep default */

  }

  const dirs = [

    path.resolve(projectPath, PATHS.TEST_CODE_DIR),

    path.resolve(projectPath, CI_TEST_SUBDIR),

  ];

  let filesPatched = 0;

  for (const dir of dirs) {

    if (!fs.existsSync(dir)) continue;

    for (const name of fs.readdirSync(dir).filter((f) => f.endsWith('.spec.ts'))) {

      const fp = path.join(dir, name);

      let content = fs.readFileSync(fp, 'utf-8');

      const before = content;

      content = content.replace(/http:\/\/localhost:(\d+)/g, (_m, p: string) => {

        if (p === port) return `http://localhost:${p}`;

        return `http://localhost:${port}`;

      });

      content = content.replace(/const BASE = '[^']*'/g, `const BASE = '${normalized.replace(/'/g, "\\'")}'`);

      content = content.replace(STRICT_MAIN_BODY, FIXED_MAIN_BODY);

      content = content.replace(

        /await expect\(page\.getByRole\('main'\)\.or\(page\.locator\('body'\)\)\)\.toBeVisible\([^)]*\)/g,

        FIXED_MAIN_BODY,

      );

      if (content !== before) {

        fs.writeFileSync(fp, content, 'utf-8');

        filesPatched++;

      }

    }

  }

  return filesPatched;

}


